config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users
    resources :products, only: [:new, :edit, :create, :update, :destroy]
    resources :bills, only: [:destroy] do
      member do
        patch :checked
      end
    end
    get 'admin' => 'application#index'
  end

  get 'sessions/new'

  resources :users, only: [:show, :new, :create, :edit, :update]
  resources :products, only: [:show, :index] do
    member do
      patch :liked
    end
  end
  resources :bills, only: [:index, :create, :edit, :update, :show]

  root 'welcome#index'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get '/auth/:provider/callback', to: 'sessions#creates'

end

app/models/bill.rb
class Bill < ActiveRecord::Base
  belongs_to :user
  belongs_to :product

  def money
    self.product.price.to_i * self.number
  end
end

app/controllers/admin/bills_controller.rb
class Admin::BillsController < ApplicationController
  def destroy
    @bill = Bill.find(params[:id])
    @bill.destroy
    respond_to do |format|
      format.js
    end
  end

  def checked
    @bill = Bill.find(params[:id])
    if @bill.checked
      @bill.checked = false
    else
      @bill.checked = true
    end
    if @bill.save
      respond_to do |format|
        format.js
      end
    end
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  def index
    @bills = current_user.my_cart
  end

  def edit
  end

  def create
    @bill = Bill.new(bill_params)
    @bill.user = User.find(params[:user_id])
    @bill.product = Product.find(params[:product_id])

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
    end
  end

  private
  def set_bill
    @bill = Bill.find(params[:id])
  end

  def bill_params
    params.require(:bill).permit(:user_id, :product_id, :number)
  end
end

app/helpers/admin/bills_helper.rb
module Admin::BillsHelper
end

app/helpers/bills_helper.rb
module BillsHelper
  def all_bills
    Bill.all
  end
end

app/views/bills/_form.html.erb
<%= form_for(@bill) do |f| %>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bills/edit.html.erb
<h1>Editing Bill</h1>

<%= render 'form' %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>

app/views/bills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Your shopping cart</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Product</th>
      <th>Number</th>
      <th>Money</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.product.name %></td>
        <td><%= bill.number %></td>
        <td><%= bill.money %></td>
        <td><%= link_to 'Edit', edit_bill_path(bill) %></td>
        <td><%= link_to 'Destroy', bill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/bills/new.html.erb
<h1>New Bill</h1>

<%= render 'form' %>

<%= link_to 'Back', bills_path %>

app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @bill.user.name %>
</p>

<p>
  <strong>Product:</strong>
  <%= @bill.product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @bill.product.price %>
</p>

<p>
  <strong>Number:</strong>
  <%= @bill.number %>
</p>

<p>
  <strong>Money:</strong>
  <%= @bill.money %>
</p>

<%= link_to 'Edit', edit_bill_path(@bill) %> |
<%= link_to 'Back', bills_path %>