config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users
    resources :products, only: [:new, :edit, :create, :update, :destroy]
    resources :bills, only: [:destroy] do
      member do
        patch :checked
      end
    end
    get 'admin' => 'application#index'
  end

  get 'sessions/new'

  resources :users, only: [:show, :new, :create, :edit, :update]
  resources :products, only: [:show, :index] do
    member do
      patch :liked
    end
  end
  resources :bills, only: [:index, :create, :edit, :update, :show]

  root 'welcome#index'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get '/auth/:provider/callback', to: 'sessions#creates'

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, presence: true

  mount_uploader :img_link, ImageUploader

  def total_like
    Liked.where(product: self).count
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :set_product, only: [:edit, :update, :destroy]
  before_action :not_admin

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.js
      else
        format.js { render inline: 'alert("' + @product.errors.full_messages.to_sentence + '");'  }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.js
      else
        format.js { render inline: "alert('khong thanh cong');"  }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.js
    end
  end

  private
  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:price, :name, :description, :make, :img_link)
  end

  def not_admin
    unless admin?
      flash[:danger] = 'nguy hiem!!!'
      redirect_to root_path
    end
  end

  def admin?
    current_user && current_user.admin
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :liked]

  def index
    if params[:query]
      @products = Product.where("name LIKE ?", "%#{params[:query]}%").paginate(:page => params[:page], :per_page => 9)
    else
      @products = Product.paginate(:page => params[:page], :per_page => 9)
    end
  end

  def show
  end

  def liked
    if current_user.liked_product(@product).count > 0
      current_user.liked_product(@product).first.destroy
    else
      Liked.create(user:current_user, product: @product)
    end
    respond_to do |format|
      format.js
    end
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_liked.html.erb
<div id="like-product-<%= product.id %>">
  <% if current_user %>
      <% if current_user.liked_product(product).empty? %>
          <%= link_to ('<i class="fa fa-heart-o">(' + product.total_like.to_s + ')</i>').html_safe, liked_product_path(product), method: :patch, remote: true %>
      <% else %>
          <%= link_to ('<i class="fa fa-heart">(' + product.total_like.to_s + ')</i>').html_safe, liked_product_path(product), method: :patch, remote: true %>
      <% end %>
  <% end %>
</div>

<div class="fb-share-button"
     data-href="<%= product_url(product) %>"
     data-layout="button_count"></div>

app/views/products/_list_products.html.erb
<% products.each do |product| %>
    <% if @mode == 'list' %>
        <%= render 'products/product_list', product: product %>
    <% else %>
        <%= render product %>
    <% end %>
<% end %>

app/views/products/_product.html.erb
<div class="col-md-4 product-info">
  <div class="product-info-img">
    <%= link_to image_tag(product.img_link.thumb.url), product_path(product), data: { no_turbolink: true } %>
    <%= render 'products/liked', product: product %>
  </div>
  <div class="product-info-text">
    <p class="product-i product-name"><%= product.name %></p>
    <p class="product-i product-make">xuat su: <%= product.make %></p>
    <p class="product-i product-price">gia: <%= product.price %></p>
    <p class="product-i product-description">mieu ta: <%= product.description %></p>
  </div>
</div>

app/views/products/_product_list.html.erb
<div class="row">
  <div class="col-md-6">
    <%= link_to image_tag(product.img_link.thumb.url), product_path(product)  %>
  </div>
  <div class="product-info-text col-md-6">
    <div class="product-i product-name"><%= product.name %>
    <%= render 'products/liked', product: product %>
    </div>
    <div class="product-i product-make">xuat su: <%= product.make %></div>
    <div class="product-i product-price">gia: <%= product.price %></div>
    <div class="product-i product-description">mieu ta: <%= product.description %></div>
  </div>
</div>
<hr>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row list-products-index">
  <% @products.each do |product| %>
      <%= render product %>
  <% end %>

  <%= will_paginate @products %>
</div>

app/views/products/liked.js.erb
$('#like-product-<%= @product.id %>').html('<%= j (render 'products/liked', product: @product) %>');

app/views/products/show.html.erb
<div class="col-md-6 product-show-info">
  <div class="product-show-info-text">
    <p class="product-name"><%= @product.name %><%= render 'products/liked', product: @product %></p>
    <p>Miêu tả: <%= @product.description %></p>
    <p class="product-price">Giá: <%= @product.price %></p>
    <p>Xuất sứ: <%= @product.make %></p>
  </div>
  <div class="product-show-info-img">
    <%= image_tag @product.img_link %>
  </div>
</div>

<% if current_user %>
    <%= form_for(Bill.new, :url => {controller: 'bills', action: 'create', user_id: current_user.id, product_id: @product.id}) do |f| %>
        <div class="field">
          <%= f.label :number %><br>
          <%= f.number_field :number %>
        </div>
        <div class="actions">
          <%= f.submit 'BUY', class: 'btn btn-success' %>
        </div>
    <% end %>
<% end %>


<div class="fb-cmt">
  <div class="fb-comments"
       data-href="<%= product_url(@product) %>"
       data-numposts="5"></div>
</div>