config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users
    resources :products, only: [:new, :edit, :create, :update, :destroy]
    resources :bills, only: [:destroy] do
      member do
        patch :checked
      end
    end
    get 'admin' => 'application#index'
  end

  get 'sessions/new'

  resources :users, only: [:show, :new, :create, :edit, :update]
  resources :products, only: [:show, :index] do
    member do
      patch :liked
    end
  end
  resources :bills, only: [:index, :create, :edit, :update, :show]

  root 'welcome#index'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get '/auth/:provider/callback', to: 'sessions#creates'

end

app/models/bill.rb
class Bill < ActiveRecord::Base
  belongs_to :user
  belongs_to :product

  def money
    self.product.price.to_i * self.number
  end
end

app/models/liked.rb
class Liked < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, presence: true

  mount_uploader :img_link, ImageUploader

  def total_like
    Liked.where(product: self).count
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :username, presence: true
  validates :email, presence: true

  def my_cart
    Bill.where(user: self)
  end

  def liked_product(product)
    Liked.where(user: self, product: product)
  end

  # def User.digest(string)
  #   cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
  #       BCrypt::Engine.cost
  #   BCrypt::Password.create(string, cost: cost)
  # end
  #
  # # Returns a random token.
  # def User.new_token
  #   SecureRandom.urlsafe_base64
  # end
  #
  # # Remembers a user in the database for use in persistent sessions.
  # def remember
  #   self.remember_token = User.new_token
  #   update_attribute(:remember_digest, User.digest(remember_token))
  # end
  #
  # # Returns true if the given token matches the digest.
  # def authenticated?(remember_token)
  #   return false if remember_digest.nil?
  #   BCrypt::Password.new(remember_digest).is_password?(remember_token)
  # end
  #
  # # Forgets a user.
  # def forget
  #   update_attribute(:remember_digest, nil)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # include Pundit
  # protect_from_forgery
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  def index
    @bills = current_user.my_cart
  end

  def edit
  end

  def create
    @bill = Bill.new(bill_params)
    @bill.user = User.find(params[:user_id])
    @bill.product = Product.find(params[:product_id])

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
    end
  end

  private
  def set_bill
    @bill = Bill.find(params[:id])
  end

  def bill_params
    params.require(:bill).permit(:user_id, :product_id, :number)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :liked]

  def index
    if params[:query]
      @products = Product.where("name LIKE ?", "%#{params[:query]}%").paginate(:page => params[:page], :per_page => 9)
    else
      @products = Product.paginate(:page => params[:page], :per_page => 9)
    end
  end

  def show
  end

  def liked
    if current_user.liked_product(@product).count > 0
      current_user.liked_product(@product).first.destroy
    else
      Liked.create(user:current_user, product: @product)
    end
    respond_to do |format|
      format.js
    end
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.visible && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user
    elsif !user.visible
      flash[:danger] = "tai khoan da bi khoa"
      render 'new'
    else
      render 'new'
    end
  end

  def creates
    auth_hash = request.env['omniauth.auth']
    # auth_hash['user_info']['email']
    if User.where(username: auth_hash['uid']).empty?
      @user = User.new
      @user.name = auth_hash['info']['name']
      @user.username = auth_hash['uid']
      @user.email = auth_hash['uid'] + '@lifetime.vn'
      @user.password = '123456'
      @user.password_confirmation = '123456'
      if @user.save
        session[:user_id] = @user.id
        redirect_to @user
      else
        flash[:danger] = 'khong thanh cong'
        redirect_to root_path
      end
    else
      session[:user_id] = User.where(username: auth_hash['uid']).first.id
      redirect_to root_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def show
  end

  def new
    @user = User.new
    if current_user
      redirect_to root_path, notice: 'you have been account!'
    end
  end

  def edit
    if current_user != @user
      redirect_to root_path, notice: 'you have not access!'
    end
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :username, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @products = Product.paginate(:page => params[:page], :per_page => 10)
    if params[:value] == 'list'
      @mode = 'list'
      render :list_grid
    elsif params[:value] == 'grid'
      @mode = 'grid'
      render :grid_list
    end
  end
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

app/helpers/admin/bills_helper.rb
module Admin::BillsHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def admin?
    current_user && (current_user.id == 1)
  end
end

app/helpers/bills_helper.rb
module BillsHelper
  def all_bills
    Bill.all
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Returns the current logged-in user (if any).
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<div class="header-nav">
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to '<i class="fa fa-home"> HoaQua</i>'.html_safe, root_path, class: 'navbar-brand active' %>
      </div>
      <ul class="nav navbar-nav">
        <li class="active"></li>
        <li><%= form_tag products_path, method: :get, class: 'form-inline pull-xs-right' do %>
              <%= text_field_tag :query, params[:query], placeholder: 'Tìm kiếm', class: 'form-control' %>
              <button type="submit" class="btn btn-success-outline">
                <i class="fa fa-search"></i>
              </button>
          <% end %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
            <li><%= link_to '<i class="fa fa-sign-out"> sign out</i>'.html_safe, logout_path, :method => :delete %></li>
            <% if admin? %>
                <li><%= link_to 'admin', admin_admin_path, class: 'btn btn-warning' %></li>
            <% else %>
                <li><%= link_to '<i class="fa fa-shopping-cart"></i>('.html_safe + current_user.my_cart.count.to_s + ')', bills_path %></li>
            <% end %>
        <% else %>
            <li><%= link_to '<i class="fa fa-user-plus"> sign up</i>'.html_safe, new_user_path %></li> |
            <li><%= link_to '<i class="fa fa-sign-in"> sign in</i>'.html_safe, login_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/admin_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hoaqua</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="container">

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hoaqua</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="container">

<%= render 'layouts/header' %>

<%= yield %>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v2.5";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

</body>
</html>